package main

import (
	"daytask/internal/config"

	"daytask/internal/http-server/handlers/task/delete"
	"daytask/internal/http-server/handlers/task/getAllTasks"
	"daytask/internal/http-server/handlers/task/getTask"
	"daytask/internal/http-server/handlers/task/save"
	"daytask/internal/http-server/handlers/task/updateTask"

	mwLogger "daytask/internal/http-server/middleware/logger"
	"daytask/internal/lib/logger/sl"
	"daytask/internal/storage/sqlite"
	"log/slog"
	"net/http"
	"os"

	"github.com/go-chi/chi/middleware"
	"github.com/go-chi/chi/v5"

	_ "daytask/docs"

	httpSwagger "github.com/swaggo/http-swagger/v2"
	//"github.com/swaggo/http-swagger/example/go-chi/docs" // docs is generated by Swag CLI, you have to import it.
)

const (
	envLocal = "local"
	envDev   = "dev"
	envProd  = "prod"
)

// @title Daytask API
// @version 1.0
// @description It's a simple task planner.

// @host petstore.swagger.io
// @BasePath /v2

func main() {
	cfg := config.MustLoad()
	log := setupLogger(cfg.Env)

	log.Info("Starting", slog.String("env", cfg.Env))
	log.Debug("debug enable")

	storage, err := sqlite.New(cfg.StoragePath)

	if err != nil {
		log.Error("failed to init storage", sl.Err(err))
		os.Exit(1)
	}
	_ = storage

	router := chi.NewRouter()

	router.Use(middleware.RequestID)
	router.Use(mwLogger.New(log))
	router.Use(middleware.Recoverer)

	router.Route("/task", func(r chi.Router) {
		r.Use(middleware.BasicAuth("daytask", map[string]string{
			cfg.HTTPServer.User: cfg.HTTPServer.Password,
		}))
		r.Post("/save", save.New(log, storage))
		r.Get("/day", getTask.New(log, storage))
		r.Get("/all", getAllTasks.New(log, storage))
		r.Delete("/", delete.New(log, storage))
		r.Patch("/", updateTask.New(log, storage))
	})

	router.Get("/swagger/*", httpSwagger.Handler())

	log.Info("starting server", slog.String("address", cfg.Address))

	srv := &http.Server{
		Addr:         cfg.Address,
		Handler:      router,
		ReadTimeout:  cfg.HTTPServer.Timeout,
		WriteTimeout: cfg.HTTPServer.Timeout,
		IdleTimeout:  cfg.HTTPServer.IdleTimeout,
	}

	if err := srv.ListenAndServe(); err != nil {
		log.Error("failed to start server")
	}

	log.Error("server stoped")
}

func setupLogger(env string) *slog.Logger {
	var log *slog.Logger

	switch env {
	case envLocal:
		log = slog.New(
			slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelDebug}))
	case envDev:
		log = slog.New(
			slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelDebug}))
	case envProd:
		log = slog.New(
			slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}))
	}

	return log
}
